name: gn_list_animator
description: "A customizable Flutter widget for animated lists with smooth index-based scrolling and staggered animations."
version: 1.0.8
homepage: none
path: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
